version: "3.7"

services:
  api:
    depends_on:
      - db
    ports:
      - "127.0.0.1:5000:5000"
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./:/home/user/api
    env_file:
      - .env
    networks:
      - user-service-network

  db:
    image: postgres:14.5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - user-service-network

  adminer:
    image: adminer:4.8.1
    restart: "always"
    ports:
      - "127.0.0.1:8765:8080"
    depends_on:
      - db 
    networks:
      - user-service-network

  ollama-api:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/usr/share/ollama/.ollama
    pull_policy: always
    tty: true
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MODELS=/usr/share/ollama/.ollama/mode
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - user-service-network

  

networks:
  user-service-network:
    external: false
    driver: bridge

volumes:
  postgres-data:
