version: "3.7"

services:
  api:
    depends_on:
      - db
    ports:
      - "127.0.0.1:5000:5000"
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./:/home/user/api
    env_file:
      - .env

  db:
    image: postgres:14.5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer:4.8.1
    restart: "always"
    ports:
      - "127.0.0.1:8765:8080"
    depends_on:
      - db

volumes:
  postgres-data:
