name: test-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            pip install poetry==1.4.2 &&
            poetry install --no-interaction --no-ansi
        - name: Run tests
          run: |
            python3 -m pytest